# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-01 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0026_auto_20171013_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturejob',
            name='block_ads',
            field=models.BooleanField(default=False),
        ),
    ]
